#
#
# --- CLIMATE ---------------------------------------------------------
#
# scaling for atmospheric CO2 radiative forcing, relative to 278 ppm
ea_radfor_scl_co2=1.0
#
# --- BIOLOGICAL NEW PRODUCTION ---------------------------------------
#
# Set no biological production
bg_par_bio_prodopt='NONE'
#
# --- DATA SAVING -----------------------------------------------------
#
# Set BASIC + full physics save level (9)
# (assume default time-series and time-slice save intervals)
bg_par_data_save_level=9
bg_ctrl_debug_lvl0=.true.
ma_debug_loop=1
#
# --- MISC ------------------------------------------------------------
#
#
# --- END -------------------------------------------------------------
#
#